version: '3.7'

networks:
  network-zabbix:
    driver: bridge

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    networks:
      - network-zabbix
    container_name: timescaledb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      TS_TUNE_MAX_CONNS: 500
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    networks:
      - network-zabbix
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: timescaledb
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
    ports:
      - '10051:10051'
    links:
      - timescaledb
    depends_on:
      - timescaledb
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    networks:
      - network-zabbix
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: timescaledb
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: "zabbix-server"
      PHP_TZ: Europe/Moscow
    ports:
      - '80:8080'
      - '443:8443'
    links:
      - timescaledb
      - zabbix-server
    depends_on:
      - timescaledb
      - zabbix-server
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
      - /var/lib/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs:ro
      - /var/lib/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys:ro
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - zabbix-web
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - timescaledb
      - zabbix-server
	    - zabbix-web
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server
